# Based on https://gist.github.com/adelmofilho/5a30a87eaf1cd4a03052f37b516d6714
services:
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - nexus-data:/nexus-data

  jenkins:
    build:
      dockerfile: ./jenkins.Dockerfile
    restart: always
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

  dind:
    image: docker:dind
    privileged: true
    restart: always
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - 2376:2376
    tty: true
    volumes:
      - jenkins-home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
      - $HOME:/home
    environment:
      - DOCKER_TLS_CERTDIR=/certs

networks:
  jenkins:

volumes:
  jenkins-home:
  jenkins-docker-certs:
  nexus-data:
